# Generated by Django 3.2.13 on 2022-06-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='emprestado',
        ),
    ]
