# Generated by Django 3.2.13 on 2022-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20220626_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='idioma',
        ),
        migrations.AddField(
            model_name='livros',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
