# Generated by Django 3.2.13 on 2022-06-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20220626_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='ano_publicacao',
            new_name='ano_edicao',
        ),
    ]
