# Generated by Django 3.2.13 on 2022-06-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_rename_ano_publicacao_livros_ano_edicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_cadastro',
        ),
    ]
